name: rabbitmq-server-snap
base: core18
version: '3.6.14'
summary: AMQP server written in Erlang
description: |
  RabbitMQ is an implementation of AMQP, the emerging standard for
  high performance enterprise messaging. The RabbitMQ server is a
  robust and scalable implementation of an AMQP broker.
license: Apache-2.0
architectures:
  - build-on: amd64
grade: devel
confinement: strict

environment:
  RABBITMQ_HOME: ${SNAP_COMMON}

apps:
  rabbitmq-server:
    command: usr/lib/erlang/bin/rabbitmq-server
    daemon: simple
  rabbitmqctl:
    command: usr/lib/erlang/bin/rabbitmqctl

parts:
  rabbitmq-server:
    plugin: make
    source: https://github.com/rabbitmq/rabbitmq-server/releases/download/rabbitmq_v3_6_14/rabbitmq-server_3.6.14.orig.tar.xz
    build-packages:
      - erlang-dev
      - erlang-nox
      - erlang-src
      - git
      - python-all
      - python-simplejson
      - rsync
      - unzip
      - xmlto
      - xsltproc
      - zip
    stage-packages:
      - adduser
      - erlang-nox
      - logrotate
      - lsb-base
      - socat
    override-build: |
      export DESTDIR=${SNAPCRAFT_PART_INSTALL}
      export PREFIX=/usr
      export PYTHON=python3
      export V=1

      make V=1
      make install
      make install-bin

  rabbitmq-server-service:
    plugin: dump
    source: .
    organize:
      rabbitmq-server.service: /lib/systemd/system/
