name: rabbitmq-server-snap
base: core18
version: '3.6.14'
summary: AMQP server written in Erlang
description: |
  RabbitMQ is an implementation of AMQP, the emerging standard for
  high performance enterprise messaging. The RabbitMQ server is a
  robust and scalable implementation of an AMQP broker.
license: Apache-2.0
architectures:
  - build-on: [amd64, i386, arm64]
grade: stable
confinement: strict

environment:
  RABBITMQ_CONF_ENV_FILE: /etc/rabbitmq/rabbitmq-env
  ERL_DIR: ${SNAP}/usr/lib

apps:
  rabbitmq-server:
    # daemon: notify
    # restart-condition: on-failure
    # restart-delay: 10s
    command: usr/lib/erlang/bin/rabbitmq-server
    # stop-command: usr/lib/erlang/bin/rabbitmqctl stop
  rabbitmqctl:
    command: usr/lib/erlang/bin/rabbitmqctl
  rabbit-env:
    command: usr/bin/snap-env

parts:
  rabbitmq-server:
    plugin: make
    source: https://github.com/rabbitmq/rabbitmq-server/releases/download/rabbitmq_v3_6_14/rabbitmq-server_3.6.14.orig.tar.xz
    build-packages:
      - erlang-dev
      - erlang-nox
      - erlang-src
      - git
      - python-all
      - python-simplejson
      - rsync
      - unzip
      - xmlto
      - xsltproc
      - zip
    stage-packages:
      - adduser
      - erlang-nox
      - logrotate
      - lsb-base
      - socat
    override-build: |
      set -e -u -x

      export DESTDIR=${SNAPCRAFT_PART_INSTALL}
      export PREFIX=/usr
      export PYTHON=python3
      export V=1

      # Patch sources
      (cd deps/rabbit; \
        cat ${SNAPCRAFT_STAGE}/0001-Set-correct-paths.patch | patch -p1)

      make
      make install
      make install-bin

      sed -i -e "s:^ERL_DIR=.*:ERL_DIR=${SNAP}:" ${SNAPCRAFT_PART_INSTALL}/usr/lib/erlang/bin/rabbitmq-defaults

  rabbitmq-patches:
    plugin: dump
    source: patches

  rabbitmq-support:
    plugin: dump
    source: assets
    organize:
      rabbitmq-env: etc/rabbitmq/rabbitmq-env
      rabbitmq-defaults: etc/rabbitmq/rabbitmq-defaults
      rabbitmq-server.service: lib/systemd/system/rabbitmq-server.service
    stage:
     - etc/rabbitmq/rabbitmq-env
     - etc/rabbitmq/rabbitmq-defaults
     - lib/systemd/system/rabbitmq-server.service

  rabbitmq-env:
    plugin: dump
    source: .
    organize:
      env.sh: usr/bin/snap-env
