name: rabbitmq-server
base: core20
version: '0.0.1'
summary: AMQP server written in Erlang
description: |
  RabbitMQ is an implementation of AMQP, the emerging standard for
  high performance enterprise messaging. The RabbitMQ server is a
  robust and scalable implementation of an AMQP broker.
source-code: https://github.com/nicolasbock/rabbitmq-server-snap
website: https://github.com/nicolasbock/rabbitmq-server-snap
issues: https://github.com/nicolasbock/rabbitmq-server-snap/issues
contact: https://github.com/nicolasbock/rabbitmq-server-snap/issues
icon: assets/logo.png
license: Apache-2.0
architectures:
  - build-on: amd64
    run-on: [arm64]
grade: stable
confinement: strict

apps:
  rabbitmq-server:
    daemon: simple
    plugs:
      - network
      - network-bind
    restart-condition: on-failure
    restart-delay: 10s
    command: bin/rabbitmq-server
    stop-command: bin/rabbitmqctl stop
  rabbitmqctl:
    plugs:
      - network
    command: bin/rabbitmqctl
  epmd:
    plugs:
      - network
      - network-bind
    command: usr/lib/erlang/bin/epmd
  rabbitmq-shell:
    command: bin/bash

  rabbitmq-diagnostics:
    command: bin/rabbitmq-diagnostics

parts:
  test:
    plugin: dump
    source: assets
    stage:
      - etc/*
      - bin/*

  rabbitmq:
    plugin: dump
    source: https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.10.7/rabbitmq-server_3.10.7-1_all.deb
    source-type: deb    
    source-checksum: sha1/026a50b240548c8216a674218856385d4c9c7d3f

  elixir:
    plugin: dump
    source: https://github.com/elixir-lang/elixir/releases/download/v1.13.3/Precompiled.zip
    source-type: zip
    source-checksum: sha1/7a2d0ff13beadcba3f566d692d960dcd785df5c8
    organize:
      '*': 'usr/'

  #   for AMD64
  #   source: https://packages.erlang-solutions.com/erlang/debian/pool/esl-erlang_25.0.2-1~ubuntu~focal_amd64.deb
  #   source-type: deb
  #   source-checksum: sha1/64db8e85bb1ae5cbbf46a75b61c423c6d5517bcd

  erlang:
    after: ["libgl1" ]
    plugin: dump
    source: https://packages.erlang-solutions.com/erlang/debian/pool/esl-erlang_25.0.2-1~ubuntu~focal_arm64.deb
    source-type: deb
    source-checksum: sha1/95922490ccab98804c6126faa6452256ff191852
    override-build: |
      snapcraftctl build
      sed -i 's|/usr/lib|$SNAP/usr/lib|g' $SNAPCRAFT_PART_INSTALL/usr/bin/erl
      sed -i 's|/usr/lib|$SNAP/usr/lib|g' $SNAPCRAFT_PART_INSTALL/usr/lib/erlang/bin/erl
    
  libgl1:
    plugin: dump
    source: http://ports.ubuntu.com/pool/main/libg/libglvnd/libgl1_1.3.1-1_arm64.deb
    source-type: deb
    source-checksum: sha1/56408a72863da278fcb038fd4e26e728362454aa


